# Generated by Django 4.1.7 on 2023-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobilenumber',
            field=models.IntegerField(null=True),
        ),
    ]
