# Generated by Django 4.1.7 on 2023-02-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
