# Generated by Django 4.1.7 on 2023-03-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
