# Generated by Django 4.1.7 on 2023-03-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
